# Example Render configuration. You will need to adjust this for the different services you run.
# Replace repo url with the repository url for your Jumpstart Pro application
services:
  - type: web
    repo: https://github.com/GITHUB_USERNAME/GITHUB_REPOSITORY # Replace this url
    name: rails
    env: ruby
    region: oregon # the region must be consistent across all services for the internal keys to be read
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString

  - type: redis
    name: redis
    region: oregon # the region must be consistent across all services for the internal keys to be read
    ipAllowList: [] # only allow internal connections
    plan: free # optional (defaults to starter)
    maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)

  # Uncomment the following blueprint if you want to enable a background worker
  # - type: worker
  #   name: sidekiq-worker
  #   env: ruby
  #   plan: starter # no free option for bg workers
  #   region: oregon # the region must be consistent across all services for the internal keys to be read
  #   buildCommand: "./bin/render-build-worker.sh"
  #   startCommand: bundle exec sidekiq -e production
  #   envVars:
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: postgres
  #         property: connectionString
  #     - key: REDIS_URL
  #       fromService:
  #         name: redis
  #         type: redis
  #         property: connectionString
  #     - key: RAILS_MASTER_KEY
  #       sync: false

databases:
  - name: postgres
    region: oregon # the region must be consistent across all services for the internal keys to be read
    ipAllowList: [] # only allow internal connections

